### ISSUE TITLE
Fix events so that correct day is selected

### ISSUE THREAD

**Issue by nikhiltaneja** [srt32/fronnect#24]
For example, right now when Saturday is selected as the event it is being displayed as Tuesday

**Comment by srt32** [comment]
Interesting. Are the values in the database right and the issue is just the
view or is the problem in the database?

**Comment by nikhiltaneja** [comment]
Problem appears to be in the database.

**Comment by srt32** [comment]
Must have broke something with a refactor.

What if you choose Friday?

**Comment by nikhiltaneja** [comment]
Looks like currently:

Friday => Tuesday
Saturday => Wednesday
Sunday => Thursday

I'm sure we'll figure it out

On Thu, Jan 2, 2014 at 6:56 AM, Simon Taranto notifications@github.comwrote:

> Must have broke something with a refactor.
> 
> What if you choose Friday?
> 
> On Thursday, January 2, 2014, Nikhil Taneja wrote:
> 
> > Problem appears to be in the database.
> > 
> > > On Jan 2, 2014, at 5:51 AM, Simon Taranto <notifications@github.com<javascript:_e({},
> > > 'cvml', 'notifications@github.com');>>
> > > wrote:
> > > 
> > > Interesting. Are the values in the database right and the issue is
> > > just
> > > the
> > > view or is the problem in the database?
> > > 
> > > On Wednesday, January 1, 2014, Nikhil Taneja wrote:
> > > 
> > > > For example, right now when Saturday is selected as the event it is
> > > > being
> > > > displayed as Tuesday
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/srt32/fronnect/issues/24>
> > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/srt32/fronnect/issues/24#issuecomment-31453507>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/srt32/fronnect/issues/24#issuecomment-31453712
> .

## 

_Nikhil Taneja_
513-739-0355
nikhil.a.taneja@gmail.com

**Comment by srt32** [comment]
That's fascinating. Some sort of day of week mismatch

**Comment by nikhiltaneja** [comment]
We still need to fix Sunday
